[bug] add libxcb-cursor0
Using python executable: /usr/bin/python3
You are missing the system library libxcb-cursor.so.0. Try installing packages such as libxcb-cursor0 or xcb-cursor
Error: Process completed with exit code 1.